--- #YAML:1.0
name:                PAR-Dist
version:             0.43
abstract:            Create and manipulate PAR distributions
license:             ~
author:              
    - Audrey Tang <cpan@audreyt.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0
    File::Temp:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
