# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PAR-Dist
version:      0.25
version_from: lib/PAR/Dist.pm
installdirs:  site
requires:
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0
    File::Temp:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
