name: PAR-Dist
module_name: PAR::Dist
version: 0.01
abstract: Create and manipulate PAR distributions
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
private:
  directory:
    - inc
generated_by: Module::Install version 0.21
